### PR TITLE
Docker developer sandbox

### PR DESCRIPTION
**Pull request by tankofzion**
## Purpose
This PR provides a containerised environment based on Docker, to ease Centrifuge developers' life. Newcomers can quickly land and work, without having to install a Rust toolchain on their host machine. Instead, they can compile and build (testing will be added soon as well) the Centrifuge chain project inside an ephemeral Docker container (called `Centrifuge Sandbox`).

## Features
The following components are implemented as part of this PR:

[x] Dockerfile with requisite Rust toolchain
[x] Bunch of Makefile scripts to ease developer's life
[x] A quick-and-dirty documentation in README.md, on how to use this sandbox
[x] A local (i.e. project-specific) Cargo index/cache, so that to avoid rebuilding it each time a sandbox is launched.

### CODE REVIEW

**Comment by asymmetric** [comment]
@tankofzion the CI failure is not related to this PR, and I'm working on it :).

**Comment by asymmetric** [comment]
@tankofzion could you rebase this on top of master, to see if the CI issues are solved?

**Comment by tankofzion** [comment]
> @tankofzion could you rebase this on top of master, to see if the CI issues are solved?

@asymmetric I took the opportunity to add a feature :) It works now. Tks

**Review by mikiquantum — APPROVED** [review]
LGTM, lets start testing it!

**Pull request merged**
