### PR TITLE
Sanity checks: re-activate Taplo

### PR DESCRIPTION
**Pull request by gpmayorga**

### CODE REVIEW

**Comment by lemunozm** [comment]
Taking the ownership of this

**Comment by lemunozm** [comment]
@gpmayorga could you give an approval? should be ready

**Review by NunoAlexandre — APPROVED** [review]
✨

**Review by wischli — APPROVED** [review]
@gpmayorga Added me as secondary GHA owner to reduce the bus factor. Thanks a lot for the fix! Enjoy your weekend!

**Pull request merged**
