### PR TITLE
Dockerfile review after CI changes

### PR DESCRIPTION
**Pull request by gpmayorga**
Removing some unnecessary lines on the Docker file and making everything more explicit

### CODE REVIEW

**Review by wischli — DISMISSED** [review]
Thanks for bringing more clarity to this grey box.

**Review by wischli — DISMISSED** [review]
Re-approving. Let's hope #1625 will fix the docs 😅

**Review by mustermeiszer — APPROVED** [review]
Approving based on internal comms.

**Review by wischli — APPROVED** [review]
Re-approving

**Pull request merged**
