### PR TITLE
Add remark pallet

### PR DESCRIPTION
**Pull request by mustermeiszer**
# Description

Adds a remark pallet. This is mostly copy paste from utilities pallet in Substrate. Test will fail and benches too. We need to add remark still. But should be easy fto fix

### CODE REVIEW

**Comment by mustermeiszer** [comment]
FYI @lemunozm

**Comment by lemunozm** [comment]
Is this related to https://github.com/centrifuge/centrifuge-chain/issues/1409?

**Comment by mustermeiszer** [comment]
Just a draft, to eliviate some work from you.

**Comment by lemunozm** [comment]
I'm a bit lost in this PR in two aspects:
- Why must we copy the `pallet-utility` instead of using it?
- What are your additions to the copied pallet? To know what things are required and what others could be removed if needed.

**Comment by lemunozm** [comment]
Closed in favor of: https://github.com/centrifuge/centrifuge-chain/pull/1479

**Pull request closed without merging**
