### PR TITLE
reformat code using cargo fmt

### PR DESCRIPTION
**Pull request by ivanceras**
The configurations used in in `rustfmt.toml` file, all source files are reformatted to use tabs instead of mix of spaces and tabs
The max_width of a line is set to 100

### CODE REVIEW

**Comment by ivanceras** [comment]
@philipstanislaus  here is the link to [substrate's config](https://github.com/paritytech/substrate/blob/master/.editorconfig)
These are the only relevant configs that is specific to the `cargo-fmt`
```
indent_style=tab
indent_size=tab
max_line_length=100
```
The rest are editor specific such as
```
tab_width=4
```
which is used by the editor on how to represent tabs shown to the user.

**Comment by ivanceras** [comment]
It looks like rustfmt will reorder the imports alphabetically by default [reorder_imports](https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#reorder_imports)
I will set the `reorder_imports = false` to mirror that of substrate. It should not change a lot of things other than the tabs and max line width of 100.

**Comment by philipstanislaus** [comment]
I'm not sure that will lead to both looking the same. 

I feel it's quite unproductive to spend too much time on `rustfmt`, what speaks against just ignoring upstream the files?

**Comment by ivanceras** [comment]
I agree, cargo fmt is doing a lot of code movement here. I will close this for now.

**Pull request closed without merging**
