### PR TITLE
Fix: Loans demo migration

### PR DESCRIPTION
**Pull request by lemunozm**
# Description

Loans for demo env have an on-chain version of 0, skipping the v2->v3 migration. This restores the correct on-chain version so that the migration can be applied.

This changes have no effect in `altair` or `centrifuge`

## Logs

```
2024-03-08 15:07:36.834  INFO main runtime_common::migrations::increase_storage_version: BumpStorageVersion: Increasing storage version of "Loans" from StorageVersion(0) to 2
2024-03-08 15:07:36.834  INFO main runtime_common::migrations::increase_storage_version: BumpStorageVersion: chain_version StorageVersion(2)
...
2024-03-08 15:07:36.835  INFO main runtime::frame-support: ⚠️ Loans declares internal migrations (which *might* execute). On-chain `StorageVersion(2)` vs current storage version `StorageVersion(3)`
2024-03-08 15:07:36.835  INFO main pallet_loans::migrations: Loans: Starting migration v2 -> v3
2024-03-08 15:07:36.835  INFO main pallet_loans::migrations: Loans: updated portfolio for pool_id: 99
2024-03-08 15:07:36.835  INFO main pallet_loans::migrations: Loans: updated portfolio for pool_id: 2666134719
2024-03-08 15:07:36.836  INFO main pallet_loans::migrations: Loans: updated portfolio for pool_id: 2869156029
2024-03-08 15:07:36.836  INFO main pallet_loans::migrations: Loans: updated portfolio for pool_id: 2659193339
2024-03-08 15:07:36.836  INFO main pallet_loans::migrations: Loans: updated portfolio for pool_id: 1
2024-03-08 15:07:36.836  INFO main pallet_loans::migrations: Loans: updated portfolio for pool_id: 75741337
2024-03-08 15:07:36.836  INFO main pallet_loans::migrations: Loans: updated portfolio for pool_id: 2
2024-03-08 15:07:36.836  INFO main pallet_loans::migrations: Loans: Migrated 7 pools
```

### CODE REVIEW

**Comment by lemunozm** [comment]
I'm not sure if we want to bump up from `1042` to `1043`, or if we do not want to because this is just a migration fix. If not, the PR is ready to be merged.

**Comment by wischli** [comment]
> I'm not sure if we want to bump up from `1042` to `1043`, or if we do not want to because this is just a migration fix. If not, the PR is ready to be merged.

We need to bump because else we cannot perform a RU.

**Review by wischli — APPROVED** [review]
Thanks for fixing this so quickly! As mentioned, we need to bump spec version of Development in order to apply this migration.

**Comment by mustermeiszer** [comment]
@lemunozm what are the logs for try-runtime on altiar and centrifuge? Could you post them here too,. THat we know all migrations are running?

**Comment by lemunozm** [comment]
This migration is not applied for `altair` which will reset the storage for loans. `centrifuge` shows:
```sh
2024-03-09 21:34:58.600  INFO main runtime::frame-support: ⚠️ Loans declares internal migrations (which *might* execute). On-chain `StorageVersion(2)` vs current storage version `StorageVersion(3)`
2024-03-09 21:34:58.600  INFO main pallet_loans::migrations: Loans: Starting migration v2 -> v3
2024-03-09 21:34:58.600  INFO main pallet_loans::migrations: Loans: updated portfolio for pool_id: 4139607887
2024-03-09 21:34:58.600  INFO main pallet_loans::migrations: Loans: Migrated 1 pools

```
But I also obtain the following unrelated error:
```sh
2024-03-09 20:34:53.362 ERROR main runtime: panicked at /Users/luis/Repos/centrifuge-chain3/runtime/common/src/migrations/local_currency.rs:312:13:
assertion failed: !has_pending_invest_orders::<T>(TargetPoolId::get())
```

Do we already know about it? @wischli

**Comment by mustermeiszer** [comment]
@lemunozm that is an outstanding investment. We can not migrate with that being present. I am asking Jay to bring that into the pool to let us proceed.

**Review by wischli — APPROVED** [review]
LGTM!

**Pull request merged**
