### PR TITLE
Upgrade to polkadot v0.9.9

### PR DESCRIPTION
**Pull request by branan**

### CODE REVIEW

**Comment by branan** [comment]
I guess we need to bump the rustc nightly we're using? This sounds like a tomorrow problem

**Review by mikiquantum — APPROVED** [review]
👍

**Comment by mikiquantum** [comment]
@branan Feel free to modify the RUST_TOOLCHAIN both https://github.com/centrifuge/centrifuge-chain/blob/07327005385bc787fdea99457338a3bfd69365c6/ci/script.sh#L5 and https://github.com/centrifuge/centrifuge-chain/blob/07327005385bc787fdea99457338a3bfd69365c6/.github/workflows/build.yml#L28 with the latest compatible one, I hope you don't have to try/error too much.

**Comment by branan** [comment]
I went with the July 28th nightly that I've been using on my laptop, looks like it got the job done in CI.

**Review by mustermeiszer — APPROVED** [review]
LGTM!

**Pull request merged**
