### PR TITLE
feat: apply polkadot v0.9.43 to docker 

### PR DESCRIPTION
**Pull request by wischli**
# Description

* Updates rococo local to polkadot v0.9.43 obtained via
```
docker run --platform=linux/amd64 parity/polkadot:v0.9.43 build-spec --disable-default-bootnode --chain rococo-local --raw > res/rococo-local.json
```
* Fixes docker compose files after [breaking changes CLI from polkadot v0.9.43](https://github.com/paritytech/polkadot/releases/tag/v0.9.43):
  * Removes `ws-port` which now is just the RPC port
  * Maps outer docker rpc port to `9944` for relay alice, `9945` for relay bob and `9946` for para charlie

## How to test
onboard.sh
```
cc_docker_image_tag="${PARA_DOCKER_IMAGE_TAG:-test-main-latest}"
parachain="${PARA_CHAIN_SPEC:-centrifuge-local}"

export PARA_DOCKER_IMAGE_TAG=$cc_docker_image_tag
export CC_DOCKER_TAG=$cc_docker_image_tag
export PARA_CHAIN_SPEC=$parachain
export DOCKER_ONBOARD=true

./scripts/init.sh start-relay-chain
./scripts/init.sh start-parachain-docker
./scripts/init.sh onboard-parachain
```

```
$ PARA_CHAIN_SPEC=altair-local ./scripts/onboard.sh
```

# Checklist:

- [ ] I have added Rust doc comments to structs, enums, traits and functions
- [ ] I have made corresponding changes to the documentation
- [ ] I have performed a self-review of my code
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by NunoAlexandre** [comment]
@wischli does it work for you locally, in your machine? This is what I am getting:

```
2023-08-15 15:15:34 <jemalloc>: MADV_DONTNEED does not work (memset will be used instead)
2023-08-15 15:15:34 <jemalloc>: (This is the expected behaviour if you are running under QEMU)
2023-08-15 15:15:34 2023-08-15 13:15:34.596  INFO main sc_cli::runner: Parity Polkadot    
2023-08-15 15:15:34 2023-08-15 13:15:34.604  INFO main sc_cli::runner: ✌️  version 0.9.43-ba42b9ce51d    
2023-08-15 15:15:34 2023-08-15 13:15:34.604  INFO main sc_cli::runner: ❤️  by Parity Technologies <admin@parity.io>, 2017-2023    
2023-08-15 15:15:34 2023-08-15 13:15:34.604  INFO main sc_cli::runner: 📋 Chain specification: Rococo Local Testnet    
2023-08-15 15:15:34 2023-08-15 13:15:34.604  INFO main sc_cli::runner: 🏷  Node name: Alice    
2023-08-15 15:15:34 2023-08-15 13:15:34.605  INFO main sc_cli::runner: 👤 Role: AUTHORITY    
2023-08-15 15:15:34 2023-08-15 13:15:34.605  INFO main sc_cli::runner: 💾 Database: RocksDb at /data/chains/rococo_local_testnet/db/full    
2023-08-15 15:15:34 2023-08-15 13:15:34.605  INFO main sc_cli::runner: ⛓  Native runtime: rococo-9430 (parity-rococo-v2.0-0.tx22.au0)    
2023-08-15 15:15:37 2023-08-15 13:15:37.202  WARN main sc_executor_wasmtime::util: You're running on a system with a broken `madvise(MADV_DONTNEED)` implementation. This will result in lower performance.    
2023-08-15 15:15:58 2023-08-15 13:15:58.156  INFO main sc_service::client::client: 🔨 Initializing Genesis block/state (state: 0xb8f0…dcd2, header-hash: 0x1f9b…6b45)    
2023-08-15 15:15:58 2023-08-15 13:15:58.208  INFO main grandpa: 👴 Loading GRANDPA authority set from genesis on what appears to be first startup.    
2023-08-15 15:16:16 2023-08-15 13:16:16.469  INFO main babe: 👶 Creating empty BABE epoch changes on what appears to be first startup.    
2023-08-15 15:16:16 2023-08-15 13:16:16.491  INFO main sub-libp2p: 🏷  Local node identity is: 12D3KooWDLpRT9KFo6pKdkmdQQt599tmqVYpoeiHemY32Gf4RUpp    
2023-08-15 15:16:16 2023-08-15 13:16:16.713  INFO main sc_sysinfo: 💻 Operating system: linux    
2023-08-15 15:16:16 2023-08-15 13:16:16.713  INFO main sc_sysinfo: 💻 CPU architecture: x86_64    
2023-08-15 15:16:16 2023-08-15 13:16:16.713  INFO main sc_sysinfo: 💻 Target environment: gnu    
2023-08-15 15:16:16 2023-08-15 13:16:16.713  INFO main sc_sysinfo: 💻 Memory: 10454MB    
2023-08-15 15:16:16 2023-08-15 13:16:16.714  INFO main sc_sysinfo: 💻 Kernel: 5.15.49-linuxkit-pr    
2023-08-15 15:16:16 2023-08-15 13:16:16.714  INFO main sc_sysinfo: 💻 Linux distribution: Ubuntu 20.04.6 LTS    
2023-08-15 15:16:16 2023-08-15 13:16:16.714  INFO main sc_sysinfo: 💻 Virtual machine: no    
2023-08-15 15:16:16 2023-08-15 13:16:16.714  INFO main sc_service::builder: 📦 Highest known block at #0    
2023-08-15 15:16:16 2023-08-15 13:16:16.720  INFO tokio-runtime-worker substrate_prometheus_endpoint: 〽️ Prometheus exporter started at 127.0.0.1:9615    
2023-08-15 15:16:16 2023-08-15 13:16:16.736  INFO                 main sc_rpc_server: Running JSON-RPC server: addr=0.0.0.0:9933, allowed origins=["*"]    
2023-08-15 15:16:16 2023-08-15 13:16:16.740  INFO                 main sc_sysinfo: 🏁 CPU score: 79.24 MiBs    
2023-08-15 15:16:16 2023-08-15 13:16:16.740  INFO                 main sc_sysinfo: 🏁 Memory score: 5.16 GiBs    
2023-08-15 15:16:16 2023-08-15 13:16:16.740  INFO                 main sc_sysinfo: 🏁 Disk score (seq. writes): 1002.40 MiBs    
2023-08-15 15:16:16 2023-08-15 13:16:16.741  INFO                 main sc_sysinfo: 🏁 Disk score (rand. writes): 330.97 MiBs    
2023-08-15 15:16:16 2023-08-15 13:16:16.741  WARN                 main polkadot_service: ⚠️  The hardware does not meet the minimal requirements for role 'Authority' find out more at:
2023-08-15 15:16:16 https://wiki.polkadot.network/docs/maintain-guides-how-to-validate-polkadot#reference-hardware    
2023-08-15 15:16:16 2023-08-15 13:16:16.800  INFO tokio-runtime-worker parachain::approval-voting: Starting with an empty approval vote DB.
2023-08-15 15:16:16 2023-08-15 13:16:16.817  INFO                 main babe: 👶 Starting BABE Authorship worker    
2023-08-15 15:16:18 2023-08-15 13:16:18.759 ERROR tokio-runtime-worker sub-authority-discovery: Failed to request addresses of authorities: Failed calling into the Substrate runtime: Error at calling runtime api: Execution failed: Execution aborted due to trap: wasm trap: call stack exhausted
2023-08-15 15:16:18 WASM backtrace:
2023-08-15 15:16:18 error while executing at wasm backtrace:
2023-08-15 15:16:18     0: <unknown>!bytes::bytes::promotable_even_drop::h00581b21643b3954
2023-08-15 15:16:18     1: 0x43ccf - <unknown>!frame_support::storage::unhashed::get::ha701021545e46384
2023-08-15 15:16:18     2: 0x40287c - <unknown>!AuthorityDiscoveryApi_authorities    
2023-08-15 15:16:18 2023-08-15 13:16:18.761 ERROR tokio-runtime-worker sub-authority-discovery: Failed to publish external addresses: Failed calling into the Substrate runtime: Error at calling runtime api: Execution failed: Execution aborted due to trap: wasm trap: call stack exhausted
2023-08-15 15:16:18 WASM backtrace:
2023-08-15 15:16:18 error while executing at wasm backtrace:
2023-08-15 15:16:18     0: <unknown>!bytes::bytes::promotable_even_drop::h00581b21643b3954
2023-08-15 15:16:18     1: 0x43ccf - <unknown>!frame_support::storage::unhashed::get::ha701021545e46384
2023-08-15 15:16:18     2: 0x40287c - <unknown>!AuthorityDiscoveryApi_authorities    
2023-08-15 15:16:21 2023-08-15 13:16:21.746  INFO tokio-runtime-worker substrate: 💤 Idle (0 peers), best: #0 (0x1f9b…6b45), finalized #0 (0x1f9b…6b45), ⬇ 0 ⬆ 0    
2023-08-15 15:16:22 2023-08-15 13:16:22.753 ERROR tokio-runtime-worker sub-authority-discovery: Failed to request addresses of authorities: Failed calling into the Substrate runtime: Error at calling runtime api: Execution failed: Execution aborted due to trap: wasm trap: call stack exhausted
2023-08-15 15:16:22 WASM backtrace:
2023-08-15 15:16:22 error while executing at wasm backtrace:
2023-08-15 15:16:22     0: <unknown>!bytes::bytes::promotable_even_drop::h00581b21643b3954
2023-08-15 15:16:22     1: 0x43ccf - <unknown>!frame_support::storage::unhashed::get::ha701021545e46384
2023-08-15 15:16:22     2: 0x40287c - <unknown>!AuthorityDiscoveryApi_authorities    
2023-08-15 15:16:22 2023-08-15 13:16:22.763 ERROR tokio-runtime-worker sub-authority-discovery: Failed to publish external addresses: Failed calling into the Substrate runtime: Error at calling runtime api: Execution failed: Execution aborted due to trap: wasm trap: call stack exhausted
2023-08-15 15:16:22 WASM backtrace:
2023-08-15 15:16:22 error while executing at wasm backtrace:
2023-08-15 15:16:22     0: <unknown>!bytes::bytes::promotable_even_drop::h00581b21643b3954
2023-08-15 15:16:22     1: 0x43ccf - <unknown>!frame_support::storage::unhashed::get::ha701021545e46384
2023-08-15 15:16:22     2: 0x40287c - <unknown>!AuthorityDiscoveryApi_authorities    
2023-08-15 15:16:26 2023-08-15 13:16:26.754  INFO tokio-runtime-worker substrate: 💤 Idle (0 peers), best: #0 (0x1f9b…6b45), finalized #0 (0x1f9b…6b45), ⬇ 0 ⬆ 0    
2023-08-15 15:16:30 2023-08-15 13:16:30.753 ERROR tokio-runtime-worker sub-authority-discovery: Failed to request addresses of authorities: Failed calling into the Substrate runtime: Error at calling runtime api: Execution failed: Execution aborted due to trap: wasm trap: call stack exhausted
2023-08-15 15:16:30 WASM backtrace:
2023-08-15 15:16:30 error while executing at wasm backtrace:
2023-08-15 15:16:30     0: <unknown>!bytes::bytes::promotable_even_drop::h00581b21643b3954
2023-08-15 15:16:30     1: 0x43ccf - <unknown>!frame_support::storage::unhashed::get::ha701021545e46384
2023-08-15 15:16:30     2: 0x40287c - <unknown>!AuthorityDiscoveryApi_authorities    
2023-08-15 15:16:30 2023-08-15 13:16:30.763 ERROR tokio-runtime-worker sub-authority-discovery: Failed to publish external addresses: Failed calling into the Substrate runtime: Error at calling runtime api: Execution failed: Execution aborted due to trap: wasm trap: call stack exhausted
2023-08-15 15:16:30 WASM backtrace:
2023-08-15 15:16:30 error while executing at wasm backtrace:
2023-08-15 15:16:30     0: <unknown>!bytes::bytes::promotable_even_drop::h00581b21643b3954
2023-08-15 15:16:30     1: 0x43ccf - <unknown>!frame_support::storage::unhashed::get::ha701021545e46384
2023-08-15 15:16:30     2: 0x40287c - <unknown>!AuthorityDiscoveryApi_authorities    
2023-08-15 15:16:31 2023-08-15 13:16:31.755  INFO tokio-runtime-worker substrate: 💤 Idle (0 peers), best: #0 (0x1f9b…6b45), finalized #0 (0x1f9b…6b45), ⬇ 0 ⬆ 0    
2023-08-15 15:16:36 2023-08-15 13:16:36.758  INFO tokio-runtime-worker substrate: 💤 Idle (0 peers), best: #0 (0x1f9b…6b45), finalized #0 (0x1f9b…6b45), ⬇ 0 ⬆ 0    
2023-08-15 15:16:41 2023-08-15 13:16:41.762  INFO tokio-runtime-worker substrate: 💤 Idle (0 peers), best: #0 (0x1f9b…6b45), finalized #0 (0x1f9b…6b45), ⬇ 0 ⬆ 0    
2023-08-15 15:16:46 2023-08-15 13:16:46.757 ERROR tokio-runtime-worker sub-authority-discovery: Failed to request addresses of authorities: Failed calling into the Substrate runtime: Error at calling runtime api: Execution failed: Execution aborted due to trap: wasm trap: call stack exhausted
2023-08-15 15:16:46 WASM backtrace:
2023-08-15 15:16:46 error while executing at wasm backtrace:
2023-08-15 15:16:46     0: <unknown>!bytes::bytes::promotable_even_drop::h00581b21643b3954
2023-08-15 15:16:46     1: 0x43ccf - <unknown>!frame_support::storage::unhashed::get::ha701021545e46384
2023-08-15 15:16:46     2: 0x40287c - <unknown>!AuthorityDiscoveryApi_authorities    
2023-08-15 15:16:46 2023-08-15 13:16:46.766 ERROR tokio-runtime-worker sub-authority-discovery: Failed to publish external addresses: Failed calling into the Substrate runtime: Error at calling runtime api: Execution failed: Execution aborted due to trap: wasm trap: call stack exhausted
2023-08-15 15:16:46 WASM backtrace:
2023-08-15 15:16:46 error while executing at wasm backtrace:
2023-08-15 15:16:46     0: <unknown>!bytes::bytes::promotable_even_drop::h00581b21643b3954
2023-08-15 15:16:46     1: 0x43ccf - <unknown>!frame_support::storage::unhashed::get::ha701021545e46384
2023-08-15 15:16:46     2: 0x40287c - <unknown>!AuthorityDiscoveryApi_authorities    
2023-08-15 15:16:46 2023-08-15 13:16:46.768  INFO tokio-runtime-worker substrate: 💤 Idle (0 peers), best: #0 (0x1f9b…6b45), finalized #0 (0x1f9b…6b45), ⬇ 0 ⬆ 0    
2023-08-15 15:16:51 2023-08-15 13:16:51.772  INFO tokio-runtime-worker substrate: 💤 Idle (0 peers), best: #0 (0x1f9b…6b45), finalized #0 (0x1f9b…6b45), ⬇ 0 ⬆ 0    
2023-08-15 15:16:56 2023-08-15 13:16:56.778  INFO tokio-runtime-worker substrate: 💤 Idle (0 peers), best: #0 (0x1f9b…6b45), finalized #0 (0x1f9b…6b45), ⬇ 0 ⬆ 0    
2023-08-15 15:17:01 2023-08-15 13:17:01.782  INFO tokio-runtime-worker substrate: 💤 Idle (0 peers), best: #0 (0x1f9b…6b45), finalized #0 (0x1f9b…6b45), ⬇ 0 ⬆ 0    
2023-08-15 15:17:06 2023-08-15 13:17:06.788  INFO tokio-runtime-worker substrate: 💤 Idle (0 peers), best: #0 (0x1f9b…6b45), finalized #0 (0x1f9b…6b45), ⬇ 0 ⬆ 0    
2023-08-15 15:17:11 2023-08-15 13:17:11.794  INFO tokio-runtime-worker substrate: 💤 Idle (0 peers), best: #0 (0x1f9b…6b45), finalized #0 (0x1f9b…6b45), ⬇ 0 ⬆ 0    

```

**Comment by NunoAlexandre** [comment]
Are you on a mac? Could you share your docker settings please? 👀 

`cat ~/Library/Group\ Containers/group.com.docker/settings.json`

**Comment by wischli** [comment]
> cat ~/Library/Group\ Containers/group.com.docker/settings.json

```
❯ cat ~/Library/Group\ Containers/group.com.docker/settings.json
{
  "backupData": false,
  "dockerAppLaunchPath": "/Applications/Docker.app",
  "displayedDeprecate1014": false,
  "diskFlush": "",
  "diskQcowCompactAfter": 0,
  "diskQcowKeepErased": 0,
  "diskQcowRuntimeAsserts": false,
  "diskStats": "",
  "vpnKitMTU": 1500,
  "vpnKitAllowedBindAddresses": "0.0.0.0",
  "vpnKitMaxConnections": 2000,
  "authDeclinedInstallSettings": false,
  "settingsVersion": 29,
  "autoStart": false,
  "activeOrganizationName": "",
  "useCredentialHelper": true,
  "credentialHelper": "docker-credential-osxkeychain",
  "disableTips": false,
  "tipLastViewedTime": 1692091658551,
  "tipLastId": 41,
  "updateAvailableTime": 1683637287844,
  "updateInstallTime": 0,
  "disableUpdate": false,
  "openUIOnStartupDisabled": true,
  "analyticsEnabled": false,
  "displayedOnboarding": true,
  "disableHardwareAcceleration": false,
  "displayRestartDialog": true,
  "displayedElectronPopup": [],
  "latestBannerKey": "",
  "acceptCanaryUpdates": false,
  "useNightlyBuildUpdates": false,
  "autoDownloadUpdates": false,
  "lastLoginDate": 0,
  "themeSource": "system",
  "containerTerminal": "integrated",
  "allowExperimentalFeatures": true,
  "enableSegmentDebug": false,
  "autoPauseTimeoutSeconds": 30,
  "dataFolder": "/Users/william/Library/Containers/com.docker.docker/Data/vms/0/data",
  "memoryMiB": 8192,
  "swapMiB": 1024,
  "cpus": 4,
  "diskSizeMiB": 61035,
  "diskTRIM": true,
  "vpnkitCIDR": "192.168.65.0/24",
  "socksProxyPort": 0,
  "proxyHttpMode": "system",
  "overrideProxyHttp": "",
  "overrideProxyHttps": "",
  "overrideProxyExclude": "",
  "overrideWindowsDockerdPort": -1,
  "filesharingDirectories": [
    "/Users",
    "/Volumes",
    "/private",
    "/tmp",
    "/var/folders"
  ],
  "kubernetesEnabled": false,
  "showKubernetesSystemContainers": false,
  "kubernetesInitialInstallPerformed": false,
  "useVirtualizationFramework": true,
  "useVirtualizationFrameworkVirtioFS": false,
  "useVirtualizationFrameworkRosetta": true,
  "useGrpcfuse": true,
  "networkType": "gvisor",
  "useVpnkit": true,
  "vpnKitMaxPortIdleTime": 300,
  "vpnKitTransparentProxy": true,
  "useWindowsContainers": false,
  "noWindowsContainers": false,
  "wslEngineEnabled": false,
  "wslEnableGrpcfuse": false,
  "runWinServiceInWslMode": false,
  "customWslDistroDir": "",
  "licenseTermsVersion": 2,
  "deprecatedCgroupv1": false,
  "useContainerdSnapshotter": false,
  "enableWasmShims": false,
  "lifecycleTimeoutSeconds": 600,
  "exposeDockerAPIOnTCP2375": false,
  "enhancedContainerIsolation": false,
  "showMacInstall": false,
  "extensionsEnabled": true,
  "onlyMarketplaceExtensions": false,
  "showExtensionsSystemContainers": false,
  "useBackgroundIndexing": true,
  "showBuildsViewFeature": false,
  "dockerBinInstallPath": "system",
  "enableDefaultDockerSocket": true,
  "updateHostsFile": false,
  "requireVmnetd": false
}
```

**Comment by NunoAlexandre** [comment]
Thanks @wischli 🙏 using your settings fixed the issues I was experiencing.

**Comment by branan** [comment]
I'm checking this on Linux-native docker for sanity

**Comment by wischli** [comment]
Superseded by #1577

**Pull request closed without merging**
