### PR TITLE
dev: Bootstrap asset-registry genesis

### PR DESCRIPTION
**Pull request by NunoAlexandre**
# Description

We add `AUSD` and `USDT` to the development runtime's `orml_asset_registry` genesis config. We also set an initial balance for all endowed account for each of those two assets. This is useful for development testing chains which get reseted occasionally and need these properties to allow for testing.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

- [x] Spin off the development chain locally and verified the registry and initial balances are correctly set
- [ ] We should test running deploying the dev chain with this new genesis to verify everything is fine

### CODE REVIEW

**Comment by NunoAlexandre** [comment]
@offerijns @onnovisser for now I've added `AUSD` and `USDT` and it assumes to be run in the rococo environment, since that assumption is required for the XCM multi-locations of those assets. Is this ok for the frontend development? Do we need other assets in?

**Comment by onnovisser** [comment]
@NunoAlexandre That sounds good. Will we be able to also fund accounts with those currencies?

**Comment by onnovisser** [comment]
Can we give a million or so of each to the dev accounts (Alice, Bob, Charlie, Dave, ...) ?

**Comment by onnovisser** [comment]
Alice: kAMx1vYzEvumnpGcd6a5JL6RPE2oerbr6pZszKPFPZby2gLLF
Bob: kALNreUp6oBmtfG87fe7MakWR8BnmQ4SmKjjfG27iVd3nuTue
Charlie: kALRWiex98BfXHsXnCRhgaQxhxKU9PNKckWzzo2Qpn2EKCarm
Dave: kAJFEnqV7LCiCaxNoSu7esnt96V7diRvYBZ9xeUHZg5k6Dqo4

**Comment by NunoAlexandre** [comment]
thanks @onnovisser and sure!

**Review by mikiquantum — APPROVED** [review]

**Pull request merged**
