### PR TITLE
fix: nuke migrations

### PR DESCRIPTION
**Pull request by mustermeiszer**
# Description
Nuke migrations check the storage for a certain prefix. As the `on_chain_strorage_version` is also stored under the prefix, we need to ommit this specific key if we check whether the storage was cleared successfully.

### CODE REVIEW

**Review by wischli — APPROVED** [review]
Thanks for the fix! Happy that the loop is only necessary for the `try-tuntime` part.

**Review by NunoAlexandre — APPROVED** [review]
Just to be sure, did you test this locally building with the try-runtime,testnet-runtime features and then run try-runtime against Algol?

**Comment by mustermeiszer** [comment]
See logs I send on slack

**Comment by NunoAlexandre** [comment]
> See logs I send on slack

yeah sorry I saw the PR first 👍

**Pull request closed without merging**
