### PR TITLE
test bench

### PR DESCRIPTION
**Pull request by mikiquantum**
# Description

Testing on comment gh action for benchmarks

# Checklist:

- [ ] I have added Rust doc comments to structs, enums, traits and functions
- [ ] I have made corresponding changes to the documentation
- [ ] I have performed a self-review of my code
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I rebased on the latest `main` branch

### CODE REVIEW

**Comment by mustermeiszer** [comment]
@mikiquantum What does this enable? Can we automatically generate benchmarks with this command? And who will be able to call it?

**Comment by mikiquantum** [comment]
@mustermeiszer this is just a fix over the workflow so I can test if it works fine. The idea is that anyone with Member role of the org can run this by adding a comment as shown above, then the logic will run this in a large runner and push the weights as an artifact associated to the run, so the result can be pulled and pushed again. In the next iteration, most likely I would like to make this automatic by having a gh bot that pushes it directly to the PR, but this requires write permissions and I would like to think this a bit more.

**Review by NunoAlexandre — DISMISSED** [review]

**Comment by mustermeiszer** [comment]
Where are the results pushed to? I mean the artifact?

**Pull request merged**
