### PR TITLE
WIP: Try again: Run unit tests in debug mode (#1238)

### PR DESCRIPTION
**Pull request by lemunozm**
Reverts centrifuge/centrifuge-chain#1272

**Be sure this PR does not break again the CI before merging** 

There is an issue with storage limitations [Slack thread](https://kflabs.slack.com/archives/C04GNE3JP6Z/p1679054894264889). Fix it before

### CODE REVIEW

**Comment by lemunozm** [comment]
So, it passes but when merged, blocks other PRs to be passed 🤦🏻‍♂️

**Comment by mustermeiszer** [comment]
I will leave this to the CI gurus as my knowledge is not really good here. ^^

**Comment by mikiquantum** [comment]
@lemunozm what is different in the PR compared to the original one?

**Comment by lemunozm** [comment]
Nothing 😵‍💫

**Comment by lemunozm** [comment]
Updated with the following changes:
- No longer needed stack limitations
- tests/benchmarks/clippy run in debug.
  - There is no problem with benchmarks because it only affects to the benchmarking we have for checking issues in benchmarks.
- Same features used across tests/benchmarks/clippy to reuse rust cached artifacts

**Comment by mustermeiszer** [comment]
@lemunozm do you still want this or can we close?

**Comment by lemunozm** [comment]
It's pretty outdated. Ideally, I wanted to wait until https://github.com/centrifuge/centrifuge-chain/pull/1551 in case we want to rescue something from it. But yes, I think it can be closed 👍🏻

**Pull request closed without merging**
