### PR TITLE
Adjust codecov settings

### PR DESCRIPTION
**Pull request by gpmayorga**
# Description

- Disable PR annotations
- Disable frailing if codecov report fails to upload

Fixes https://kflabs.slack.com/archives/C04GNE3JP6Z/p1712311488621489

### CODE REVIEW

**Review by lemunozm — APPROVED** [review]
❤️

**Comment by lemunozm** [comment]
I still see the error in the PR 🤔. Does the fix only apply when it's merged?

**Comment by gpmayorga** [comment]
Making some more adjustments, it should be gone when the checks pass

**Comment by lemunozm** [comment]
Working as expected 🎉  But I think to be 100% sure we need to create a PR with lines of code changed and not tested 😆 

Thanks! I think we can merge this now 👍🏻

**Review by lemunozm — APPROVED** [review]

**Review by wischli — APPROVED** [review]

**Pull request merged**
