### PR TITLE
Fix RustDocs & AlwaysPass codecov patch check

### PR DESCRIPTION
**Pull request by gpmayorga**
# Description
https://kflabs.slack.com/archives/C04GJQAM9P0/p1718188938855999
Fix docs deployments, broken for about a month due to a GHA module upgrade

### CODE REVIEW

**Comment by lemunozm** [comment]
How can we have the `fmt` job failing but passing in `main`? 🤔

**Comment by gpmayorga** [comment]
I'm absolutely puzzled. It's complaining about code lines from 2 years ago.

**Comment by gpmayorga** [comment]
#1871 should fix it...

**Comment by gpmayorga** [comment]
We'll have to wait for William to be back but it's not urgent, every time this PR gets updated with the latest from main the docs are automatically deployed by the workflow as this is treated as a special branch.

**Review by lemunozm — APPROVED** [review]
Let's merge it!

**Review by wischli — APPROVED** [review]
Thanks for the fix!

**Pull request merged**
