### PR TITLE
Remove dependency warnings due to `codec` aliases in workspace dependencies

### PR DESCRIPTION
**Pull request by lemunozm**
# Description

After some crates use workspace dependency, we are seeing a lot of warnings when compiling, [this cargo issue](https://github.com/rust-lang/cargo/issues/12546). It seems that it can not have an alias dependency if using workspace dependencies. This PR adds support to use the original dependency name instead of the aliased one.

## Changes and Descriptions

- [x] Remove unused workspace dependencies.
- [x] `codec` by `parity-scale-codec` in crates that are currently using workspace dependencies.
- [x] `codec` by `parity-scale-codec` in `libs/*` crates (for future workspace usage)
- [x] `codec` by `parity-scale-codec` in `pallets/*` crates (for future workspace usage)

### CODE REVIEW

**Review by NunoAlexandre — APPROVED** [review]
✨

**Review by wischli — DISMISSED** [review]
Awesome, thanks a lot for this!

**Comment by lemunozm** [comment]
Added the change to all pallets. I've done it automatically with a script, so maybe some line has become quite long.

Should now be ready to be merged!

**Review by wischli — APPROVED** [review]

**Review by mustermeiszer — APPROVED** [review]
Thanks! Nice clean, up!

**Comment by lemunozm** [comment]
@cdamian I think we need yours too 🙏🏻

**Review by hieronx — APPROVED** [review]

**Comment by mustermeiszer** [comment]
Force merging as @cdamian is on vacation and all others are approving!

**Pull request merged**
