### PR TITLE
Re-generate runtime weights

### PR DESCRIPTION
**Pull request by mikiquantum**
## Description

- [x] Regenerate weights for Altair
- [x] Regenerate weights for Centrifuge
- [x] Fix rustdoc build 
- [x] Fix docker free space build

### CODE REVIEW

**Review by NunoAlexandre — APPROVED** [review]

**Review by wischli — DISMISSED** [review]
LGTM! Weights seem to have increased by ~2x 👀

**Review by NunoAlexandre — DISMISSED** [review]

**Comment by mikiquantum** [comment]
@wischli Yes, the old weights were calculated in my local, which has higher resources than the CI one. The CI one matches the specs of the recommended hardware for collators.

**Review by wischli — APPROVED** [review]
LGTM!

**Review by branan — APPROVED** [review]

**Pull request merged**
