### PR TITLE
Remove nft, nft-sales & migration pallets

### PR DESCRIPTION
**Pull request by lemunozm**
# Description

Remove deprecated pallets from our codebase.

- [x] Check `pallet-nft` storage for altair & centrifuge chains
- [x] Check `pallet-nft-sales` storage for altair & centrifuge chains
- [x] Check `pallet-nft-migration` storage for altair & centrifuge chains

### CODE REVIEW

**Comment by lemunozm** [comment]
Require migrations to remove:
- pallet-nft-sales in `altair` 
- pallet-migration in `altair` and `centrifuge`

**Comment by lemunozm** [comment]
Migrations manually tested:
- [ ] `altair`
- [ ] `centrifuge`

**Review by wischli — APPROVED** [review]
I suppose spring cleaning came early, 30k lines gone in the wind. I am happy the `KillPallet` alteration of your nuke migration is getting more use!

**Comment by lemunozm** [comment]
Yeah! Most of those lines where from the state used in migration pallets. But anyway, 30k lines are a great cleanup! I hope we use more `KillPallet` 🔪

**Pull request merged**
