### PR TITLE
Oracles: Protect from configuring with duplicated feeders

### PR DESCRIPTION
**Pull request by lemunozm**
# Description

We should avoid configuring the feeders with a vector to prevent the caller from adding duplicated feeders. Instead of checking duplications in runtime, we can ensure this behavior in the type system using a set.

* Depends on https://github.com/centrifuge/centrifuge-chain/pull/1658

### CODE REVIEW

**Review by cdamian — APPROVED** [review]
LGTM

**Review by NunoAlexandre — DISMISSED** [review]
Way to go 👌

**Review by mustermeiszer — DISMISSED** [review]
LGTM!

**Comment by lemunozm** [comment]
Thanks! Waiting to #1658 first

**Review by mustermeiszer — APPROVED** [review]

**Pull request merged**
